# Generated by Django 4.0.2 on 2023-01-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CxcMovi',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('estado', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de vencimiento')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('abono', models.FloatField()),
                ('descuento', models.FloatField()),
                ('valorLetras', models.CharField(max_length=250, verbose_name='Valor en letras')),
                ('observacion', models.CharField(max_length=250, verbose_name='Observacion')),
                ('formaPago', models.CharField(max_length=250, verbose_name='Forma de pago')),
                ('xmlEstado', models.BooleanField(default=False)),
                ('cufe', models.CharField(blank=True, max_length=350, null=True, verbose_name='cufe')),
                ('qr', models.CharField(blank=True, max_length=350, null=True, verbose_name='qr')),
                ('statusFac', models.CharField(blank=True, max_length=350, null=True, verbose_name='qr')),
                ('valorReteFuente', models.FloatField()),
                ('valorReteIca', models.FloatField()),
                ('valorReteCree', models.FloatField()),
                ('tipoFactura', models.IntegerField(choices=[(1, 'Electronica'), (2, 'POS')])),
                ('correoEnviado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CxcMovi',
                'verbose_name_plural': 'CxcMovi',
            },
        ),
        migrations.CreateModel(
            name='CxcMoviDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('lote', models.CharField(max_length=50, verbose_name='lote')),
                ('iva', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.cxcmovi')),
            ],
            options={
                'verbose_name': 'CxcMoviDetalle',
                'verbose_name_plural': 'CxcMoviDetalles',
            },
        ),
    ]
