# Generated by Django 4.0.2 on 2023-01-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxcmovidetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productos'),
        ),
        migrations.AddField(
            model_name='cxcmovi',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='cxcmovi',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.terceros'),
        ),
    ]
