# Generated by Django 4.0.2 on 2023-01-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Asiento contable:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('mes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mes:')),
                ('anio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Año:')),
                ('totalDebito', models.FloatField(verbose_name='Total crédito:')),
                ('totalCredito', models.FloatField(verbose_name='Total débito:')),
            ],
            options={
                'verbose_name': 'asiento',
                'verbose_name_plural': 'asientos',
                'db_table': 'asiento',
            },
        ),
        migrations.CreateModel(
            name='asientoDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debito', models.FloatField(default=0, verbose_name='Débito')),
                ('credito', models.FloatField(default=0, verbose_name='credito')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('mes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mes:')),
                ('anio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Año:')),
            ],
            options={
                'verbose_name': 'asientoDetalle',
                'verbose_name_plural': 'asientoDetalles',
                'db_table': 'asientoDetalle',
            },
        ),
        migrations.CreateModel(
            name='CombrobantesDetalleContable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('debito', models.FloatField(default=0, verbose_name='Débito')),
                ('credito', models.FloatField(default=0, verbose_name='credito')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'CombrobantesDetalleContable',
                'verbose_name_plural': 'CombrobantesDetalleContables',
                'db_table': 'CombrobantesDetalleContables',
            },
        ),
        migrations.CreateModel(
            name='puc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDeCuenta', models.CharField(choices=[('CLASES', 'CLASE'), ('SUBCLASE', 'SUBCLASE'), ('GRUPO', 'GRUPO'), ('CUENTAS', 'CUENTAS'), ('SUBCUENTA', 'SUBCUENTA')], max_length=15, verbose_name='Tipo de Cuenta:')),
                ('naturaleza', models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], max_length=20, verbose_name='Naturaleza de la Cuenta:')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la cuenta:')),
                ('codigo', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Codigo de la cuenta:')),
                ('estadoFinanciero', models.BooleanField(blank=True, null=True)),
                ('estadoResultado', models.BooleanField(blank=True, null=True)),
                ('padre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Padre:')),
            ],
            options={
                'verbose_name': 'puc',
                'verbose_name_plural': 'puc',
                'db_table': 'puc',
            },
        ),
        migrations.CreateModel(
            name='ComprobantesContable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero:')),
                ('consecutivo', models.IntegerField(blank=True, null=True, verbose_name='Consecutivo:')),
                ('referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia')),
                ('total', models.FloatField(default=0, verbose_name='Total Comprobante:')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('mes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mes:')),
                ('anio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Año:')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante_empresa', to='configuracion.empresa')),
                ('numeracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeracion_comprobante', to='configuracion.numeracion')),
            ],
            options={
                'verbose_name': 'ComprobantesContable',
                'verbose_name_plural': 'ComprobantesContables',
                'db_table': 'comprobantesContables',
            },
        ),
    ]
