# Generated by Django 4.0.2 on 2023-01-07 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0001_initial'),
        ('configuracion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantescontable',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combrobantesdetallecontable',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante_detalle', to='contabilidad.comprobantescontable'),
        ),
        migrations.AddField(
            model_name='combrobantesdetallecontable',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cd_cuenta', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='combrobantesdetallecontable',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cd_tercero', to='configuracion.terceros'),
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiento_detalle', to='contabilidad.asiento'),
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiento_cuenta', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiento_tercero', to='configuracion.terceros'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiento_empresa', to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiento_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
