# Generated by Django 4.0.2 on 2023-01-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puc',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la cuenta:'),
        ),
    ]
