# Generated by Django 4.0.2 on 2023-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_puc_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='concepto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Concepto:'),
        ),
    ]
