# Generated by Django 4.0.2 on 2023-01-31 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_asiento_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaNecesaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre:')),
                ('isCompra', models.BooleanField(default=False)),
                ('isVenta', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.puc')),
            ],
            options={
                'verbose_name': 'CuentaNecesaria',
                'verbose_name_plural': 'CuentaNecesarias',
                'db_table': 'cuentanecesaria',
            },
        ),
    ]
