# Generated by Django 4.0.2 on 2023-03-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_cuentanecesaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentanecesaria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre         : '),
        ),
    ]
