# Generated by Django 4.0.2 on 2023-03-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_cuentanecesaria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puc',
            name='padre',
            field=models.IntegerField(),
        ),
    ]
