# Generated by Django 4.0.2 on 2023-03-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_puc_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puc',
            name='padre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
