# Generated by Django 4.0.2 on 2023-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_alter_puc_tipodecuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientodetalle',
            name='concepto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Concepto:'),
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='tipo',
            field=models.CharField(default='SI', max_length=50, verbose_name='tipo:'),
            preserve_default=False,
        ),
    ]
