# Generated by Django 4.0.2 on 2023-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_asientodetalle_concepto_asientodetalle_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(default='', max_length=50, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Asiento contable:'),
        ),
    ]
