# Generated by Django 4.0.2 on 2023-04-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_asiento_tipo_alter_asiento_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combrobantesdetallecontable',
            old_name='descripcion',
            new_name='concepto',
        ),
        migrations.RenameField(
            model_name='combrobantesdetallecontable',
            old_name='fecha',
            new_name='fechaMovi',
        ),
        migrations.RenameField(
            model_name='comprobantescontable',
            old_name='fecha',
            new_name='fechaRegistro',
        ),
        migrations.RemoveField(
            model_name='comprobantescontable',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='comprobantescontable',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='comprobantescontable',
            name='referencia',
        ),
        migrations.AddField(
            model_name='combrobantesdetallecontable',
            name='docReferencia',
            field=models.CharField(default=None, max_length=50, verbose_name='Doc ref:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combrobantesdetallecontable',
            name='naturaleza',
            field=models.CharField(choices=[('D', 'DÉBITO'), ('C', 'CRÉDITO')], default=None, max_length=50, verbose_name='Naturaleza:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobantescontable',
            name='tipo',
            field=models.CharField(blank=True, choices=[('MC', 'Movimiento contable'), ('NTC', 'Nota contable')], max_length=50, null=True, verbose_name='Tipo movimiento:'),
        ),
    ]
