# Generated by Django 4.0.2 on 2023-04-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_rename_descripcion_combrobantesdetallecontable_concepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='docReferencia',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='docRefencia:'),
        ),
        migrations.AddField(
            model_name='asientodetalle',
            name='docReferencia',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='docRefencia:'),
        ),
    ]
