# Generated by Django 4.0.2 on 2023-05-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_asiento_docreferencia_asientodetalle_docreferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientodetalle',
            name='saldo',
            field=models.FloatField(default=0, verbose_name='credito'),
        ),
    ]
