# Generated by Django 4.0.2 on 2023-05-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_balanceprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceprueba',
            name='padre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
