# Generated by Django 4.0.2 on 2023-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_alter_balanceprueba_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='puc',
            name='grupoReporte',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Grupo Reporte:'),
        ),
        migrations.AlterField(
            model_name='puc',
            name='estadoFinanciero',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='puc',
            name='estadoResultado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
