# Generated by Django 4.0.2 on 2023-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_puc_gruporeporte_alter_puc_estadofinanciero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puc',
            name='grupoReporte',
            field=models.CharField(blank=True, choices=[('EF1', 'ACTIVOS CORRIENTES'), ('EF2', 'ACTIVOS NO CORRIENTES'), ('EF3', 'PASIVOS CORRIENTES'), ('EF4', 'PASIVOS NO CORRIENTES'), ('EF5', 'PATRIMONIO'), ('RI1', 'INGRESOS DE ACTIVIDADES CONTINUADAS'), ('RI2', 'COSTOS DE ACTIVIDADES CONTINUADAS'), ('RI3', 'GASTOS DE ADMINISTRACIÓN'), ('RI4', 'GASTOS FINANCIEROS'), ('RI5', 'INGRESOS FINANCIEROS'), ('RI6', 'IMPUESTO A LA RENTA Y COMPLEMENTARIOS')], max_length=5, null=True, verbose_name='Grupo Reporte:'),
        ),
    ]
