# Generated by Django 4.0.2 on 2023-05-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0020_alter_puc_gruporeporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padre', models.IntegerField(blank=True, null=True)),
                ('saldo', models.FloatField(default=0)),
                ('grupo', models.CharField(blank=True, choices=[('EF1', 'ACTIVOS CORRIENTES'), ('EF2', 'ACTIVOS NO CORRIENTES'), ('EF3', 'PASIVOS CORRIENTES'), ('EF4', 'PASIVOS NO CORRIENTES'), ('EF5', 'PATRIMONIO')], max_length=5, null=True, verbose_name='Grupo Reporte:')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.puc')),
            ],
            options={
                'verbose_name': 'Estado financiero',
                'verbose_name_plural': 'Estados Financieros',
                'db_table': 'estadoFinanciero',
            },
        ),
    ]
