# Generated by Django 4.0.2 on 2023-06-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_estadofinanciero'),
    ]

    operations = [
        migrations.AddField(
            model_name='puc',
            name='rete_compras',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='puc',
            name='rete_ventas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
