# Generated by Django 4.0.2 on 2023-07-25 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0024_alter_numeracion_tipodocumento'),
        ('contabilidad', '0022_puc_rete_compras_puc_rete_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero:')),
                ('consecutivo', models.IntegerField(blank=True, null=True, verbose_name='Consecutivo:')),
                ('fecha', models.DateField(verbose_name='Fecha:')),
                ('monto', models.FloatField()),
                ('concepto', models.TextField()),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslado_cuenta_destino', to='contabilidad.puc')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslado_cuenta_origen', to='contabilidad.puc')),
                ('numeracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeracion_traslado', to='configuracion.numeracion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslado_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traslado',
                'verbose_name_plural': 'Traslados',
            },
        ),
    ]
