# Generated by Django 4.0.2 on 2023-07-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0024_cajamenor_pagocajamenor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajamenor',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='fecha apertura:'),
        ),
    ]
