# Generated by Django 4.0.2 on 2023-07-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0025_alter_cajamenor_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajamenor',
            name='numero_str',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagocajamenor',
            name='numero_str',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
