# Generated by Django 4.0.2 on 2023-08-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0026_cajamenor_numero_str_pagocajamenor_numero_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientodetalle',
            name='conciliado',
            field=models.BooleanField(default=False),
        ),
    ]
