# Generated by Django 4.0.2 on 2023-03-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_alter_numeracion_tipodocumento_and_more'),
        ('docVentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cxcmovidetalle',
            old_name='totalIva',
            new_name='subtotal',
        ),
        migrations.AddField(
            model_name='cxcmovi',
            name='valorIva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cxcmovidetalle',
            name='laboratorio',
            field=models.CharField(default=0, max_length=50, verbose_name='Laboratorio : '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cxcmovidetalle',
            name='valorCompra',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cxcmovidetalle',
            name='lote',
            field=models.CharField(max_length=50, verbose_name='lote: '),
        ),
        migrations.CreateModel(
            name='RetencionCxc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base', models.FloatField()),
                ('procentaje', models.FloatField()),
                ('total', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retencion_cxc', to='docVentas.cxcmovi')),
                ('retencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reteciones_cxc', to='configuracion.retenciones')),
            ],
            options={
                'verbose_name': 'Retenciones facturas ',
                'verbose_name_plural': 'Retenciones Documentos Ventas',
            },
        ),
        migrations.CreateModel(
            name='ImpuestoCxc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base', models.FloatField()),
                ('procentaje', models.FloatField()),
                ('total', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuesto_cxc', to='docVentas.cxcmovi')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_cxc', to='configuracion.impuestos')),
            ],
            options={
                'verbose_name': 'Impuesto factura',
                'verbose_name_plural': 'Impuestos Facturas',
            },
        ),
    ]
