# Generated by Django 4.0.2 on 2023-03-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0002_rename_totaliva_cxcmovidetalle_subtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cxcmovi',
            old_name='valorReteCree',
            new_name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cxcmovi',
            name='valorReteIca',
        ),
        migrations.AddField(
            model_name='cxcmovidetalle',
            name='vence',
            field=models.DateField(default=None, verbose_name='vencimiento:'),
            preserve_default=False,
        ),
    ]
