# Generated by Django 4.0.2 on 2023-03-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0004_cxcmovi_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxcmovi',
            name='proformada',
            field=models.BooleanField(default=False),
        ),
    ]
