# Generated by Django 4.0.2 on 2023-03-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0005_cxcmovi_proformada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestocxc',
            name='procentaje',
            field=models.FloatField(verbose_name='porcentaje'),
        ),
        migrations.AlterField(
            model_name='retencioncxc',
            name='procentaje',
            field=models.FloatField(verbose_name='porcentaje'),
        ),
    ]
