# Generated by Django 4.0.2 on 2023-03-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0006_alter_impuestocxc_procentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxcmovi',
            name='hora',
            field=models.TimeField(auto_now=True, verbose_name='Hora'),
        ),
    ]
