# Generated by Django 4.0.2 on 2023-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0007_cxcmovi_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxcmovi',
            name='transaccionID',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='transaccionID'),
        ),
        migrations.AlterField(
            model_name='cxcmovi',
            name='cufe',
            field=models.CharField(blank=True, max_length=3050, null=True, verbose_name='cufe'),
        ),
        migrations.AlterField(
            model_name='cxcmovi',
            name='qr',
            field=models.CharField(blank=True, max_length=3050, null=True, verbose_name='qr'),
        ),
    ]
