# Generated by Django 4.0.2 on 2023-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0008_cxcmovi_transaccionid_alter_cxcmovi_cufe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxcmovi',
            name='qr',
            field=models.TextField(blank=True, null=True, verbose_name='qr'),
        ),
    ]
