# Generated by Django 4.0.2 on 2023-03-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0010_cxcmovi_enviadadian'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxcmovi',
            name='isElectronica',
            field=models.BooleanField(default=False),
        ),
    ]
