# Generated by Django 4.0.2 on 2023-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0014_remove_cxcmovidetalle_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxcmovi',
            name='numero_nota_credito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='numero nota credito'),
        ),
        migrations.AddField(
            model_name='cxcmovi',
            name='numero_nota_debito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='numero nota debito'),
        ),
        migrations.AddField(
            model_name='cxcmovi',
            name='valor_nota_credito',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cxcmovi',
            name='valor_nota_debito',
            field=models.FloatField(default=0),
        ),
    ]
