# Generated by Django 4.0.2 on 2023-06-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0016_cxcventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxcmovi',
            name='cufe',
            field=models.TextField(blank=True, null=True, verbose_name='cufe'),
        ),
    ]
