# Generated by Django 4.0.2 on 2023-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0017_alter_cxcmovi_cufe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxcventas',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación:'),
        ),
    ]
