# Generated by Django 4.0.2 on 2023-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0019_cxcventas_valordescuento_alter_cxcmovi_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosventas',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
