# Generated by Django 4.0.2 on 2023-08-18 17:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0024_alter_numeracion_tipodocumento'),
        ('stock', '0033_cxpcompras_notacredito'),
        ('docVentas', '0023_notacredito_enviadadian_notacredito_iselectronica'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleNotaCredito',
            new_name='DetalleNotaCreditoVentas',
        ),
        migrations.RenameModel(
            old_name='NotaCredito',
            new_name='NotaCreditoVentas',
        ),
    ]
