# Generated by Django 4.0.2 on 2023-08-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0024_rename_detallenotacredito_detallenotacreditoventas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenotacreditoventas',
            name='valorCompra',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
