# Generated by Django 4.0.2 on 2023-09-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_alter_productos_cum'),
        ('docVentas', '0027_cotizacioninformal_detallecotizacioninformal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxcmovidetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_detalle_factura', to='stock.productos'),
        ),
    ]
