# Generated by Django 4.0.2 on 2024-01-15 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_ajustestock_ajustedetalle'),
        ('configuracion', '0028_alter_notificacion_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docVentas', '0030_notacreditoventas_transaccionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevaCotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecutivo', models.IntegerField()),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='numero')),
                ('prefijo', models.CharField(max_length=50, verbose_name='prefijo')),
                ('valor', models.FloatField()),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now=True, verbose_name='Hora')),
                ('descuento', models.FloatField(default=0)),
                ('valorDomicilio', models.FloatField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=350, null=True, verbose_name='Observacion')),
                ('valorIva', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('valorReteFuente', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_cotizacion', to='configuracion.terceros')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion_formaPago', to='configuracion.formapago')),
                ('numeracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeracion_cotizacion', to='configuracion.numeracion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizacione_vendedor', to='configuracion.vendedoresclientes')),
            ],
            options={
                'verbose_name': 'NuevaCotizacion',
                'verbose_name_plural': 'NuevaCotizacion',
            },
        ),
        migrations.CreateModel(
            name='NuevaCotizacionDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorCompra', models.FloatField()),
                ('valor', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('descuento', models.FloatField(default=0)),
                ('iva', models.FloatField(default=0)),
                ('total', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_cotizacion', to='docVentas.nuevacotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_detalle_cotizacion', to='stock.productos')),
            ],
            options={
                'verbose_name': 'NuevaCotizacion',
                'verbose_name_plural': 'NuevaCotizacion',
            },
        ),
        migrations.RemoveField(
            model_name='detallecotizacioninformal',
            name='cotizacion',
        ),
        migrations.DeleteModel(
            name='CotizacionInformal',
        ),
        migrations.DeleteModel(
            name='DetalleCotizacionInformal',
        ),
    ]
