# Generated by Django 4.0.2 on 2023-12-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVentas', '0031_nuevacotizacion_nuevacotizaciondetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevacotizacion',
            name='valorReteFuente',
            field=models.FloatField(default=0),
        ),
    ]
