# Generated by Django 4.0.2 on 2023-01-11 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0007_alter_terceros_codigopostal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Bogeda')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
            },
        ),
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='ATIPO')),
                ('c_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_tipo', to='contabilidad.puc')),
            ],
            options={
                'verbose_name': 'tipoProducto',
                'verbose_name_plural': 'tiposDeProductos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=150, verbose_name='Marca')),
                ('Filtro', models.CharField(max_length=150, verbose_name='Filtro')),
                ('invima', models.CharField(blank=True, max_length=50, null=True)),
                ('cum', models.CharField(blank=True, max_length=50, null=True)),
                ('valorCompra', models.FloatField()),
                ('valorVenta', models.FloatField()),
                ('valorventa1', models.FloatField()),
                ('valorventa2', models.FloatField()),
                ('fv', models.BooleanField(default=True)),
                ('regulado', models.BooleanField(default=False)),
                ('valorRegulacion', models.FloatField(default=0)),
                ('stock_inicial', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=0)),
                ('stock_max', models.IntegerField(default=0)),
                ('habilitado', models.BooleanField(default=True)),
                ('codigoDeBarra', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad', models.CharField(max_length=150, verbose_name='Unidad')),
                ('creado', models.DateTimeField(auto_now=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
                ('nombreymarcaunico', models.CharField(blank=True, max_length=900, null=True, unique=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.bodega')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.impuestos')),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.tipoproducto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripcion')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo')),
                ('unidades', models.IntegerField()),
                ('balance', models.IntegerField(default=0)),
                ('precio', models.FloatField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardexs_bodega', to='stock.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardexs_producto', to='stock.productos')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.terceros')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
                'db_table': 'kardexs',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('unidades', models.IntegerField()),
                ('lote', models.CharField(max_length=50, verbose_name='lote')),
                ('estado', models.BooleanField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_bodega', to='stock.bodega')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.productos')),
            ],
            options={
                'verbose_name': 'Iventario',
                'verbose_name_plural': 'Iventarios',
            },
        ),
    ]
