# Generated by Django 4.0.2 on 2023-01-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='valorCompra',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
