# Generated by Django 4.0.2 on 2023-01-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_inventario_valorcompra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterField(
            model_name='inventario',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_producto', to='stock.productos'),
        ),
    ]
