# Generated by Django 4.0.2 on 2023-01-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_inventario_options_alter_inventario_idproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='marca',
        ),
    ]
