# Generated by Django 4.0.2 on 2023-01-20 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0008_alter_retencionesclientes_options_and_more'),
        ('stock', '0005_ingreso_notadebito_ordendecompra_tipotransaccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valorUnidad', models.FloatField()),
                ('descuento', models.FloatField(default=0)),
                ('iva', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalle de Ordenes',
                'db_table': 'ordendetalle',
            },
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='producto',
        ),
        migrations.DeleteModel(
            name='TipoTransaccion',
        ),
        migrations.RenameField(
            model_name='pagoscompras',
            old_name='dto',
            new_name='descuento',
        ),
        migrations.RemoveField(
            model_name='notacredito',
            name='nuemracion',
        ),
        migrations.AddField(
            model_name='notacredito',
            name='numeracion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito_numeracion', to='configuracion.numeracion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscompras',
            name='tipoTransaccion',
            field=models.BooleanField(choices=[('0', 'Pago sin relación'), ('1', 'Pago con relación')], default=1, verbose_name='Tipo de transaccion:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cxpcompras',
            name='formaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cxpcompras_formaPago', to='configuracion.formapago'),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_NotaCredito', to='stock.notacredito'),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prdoucto_notaCreditoDetalle', to='stock.productos'),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='valorUnidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='impuestoingreso',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_ingreso', to='configuracion.impuestos'),
        ),
        migrations.AlterField(
            model_name='impuestoorden',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_orden', to='configuracion.impuestos'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='formaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingreso_formaPago', to='configuracion.formapago'),
        ),
        migrations.AlterField(
            model_name='ingresodetalle',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresodetalle',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento:'),
        ),
        migrations.AlterField(
            model_name='ingresodetalle',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingreso_detalle', to='stock.ingreso'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito_ingreso', to='stock.ingreso'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='observacion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito_proveedor', to='configuracion.terceros'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notaDebito_ingreso', to='stock.ingreso'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='iva',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='numeracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notaDebito_numeracion', to='configuracion.numeracion'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='observacion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notaDebito_proveedor', to='configuracion.terceros'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='retencion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notaDebito_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='valorTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notadebitodetalle',
            name='iva',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notadebitodetalle',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_notaDebito', to='stock.notadebito'),
        ),
        migrations.AlterField(
            model_name='notadebitodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_notaDebito', to='stock.productos'),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='formaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_formaPago', to='configuracion.formapago'),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Orden_proveedor', to='configuracion.terceros'),
        ),
        migrations.AlterField(
            model_name='pagoscompras',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_ingreso', to='stock.ingreso'),
        ),
        migrations.AlterField(
            model_name='retencioningreso',
            name='retencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reteciones_ingreso', to='configuracion.retenciones'),
        ),
        migrations.AlterField(
            model_name='retencionorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retencion_orden', to='stock.ordendecompra'),
        ),
        migrations.AlterField(
            model_name='retencionorden',
            name='retencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_orden', to='configuracion.retenciones'),
        ),
        migrations.AlterModelTable(
            name='retencionorden',
            table='retencionesorden',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_orden', to='stock.ordendecompra'),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleOrden_productos', to='stock.productos'),
        ),
    ]
