# Generated by Django 4.0.2 on 2023-01-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_alter_retencionesclientes_options_and_more'),
        ('stock', '0009_alter_cxpcompras_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='ingresada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cxpcompras',
            name='formaPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cxpcompras_formaPago', to='configuracion.formapago'),
        ),
        migrations.AlterField(
            model_name='cxpcompras',
            name='observacion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Observación:'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='observacion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='observacion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='observacion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='observacion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
