# Generated by Django 4.0.2 on 2023-01-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_ordendecompra_ingresada_alter_cxpcompras_formapago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresodetalle',
            name='subtotal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresodetalle',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
