# Generated by Django 4.0.2 on 2023-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_ingresodetalle_subtotal_ingresodetalle_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='fecha:'),
        ),
    ]
