# Generated by Django 4.0.2 on 2023-01-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_terceros_isretencion'),
        ('stock', '0012_kardex_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_impuesto', to='configuracion.impuestos'),
        ),
    ]
