# Generated by Django 4.0.2 on 2023-01-31 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_terceros_isretencion'),
        ('contabilidad', '0005_cuentanecesaria'),
        ('stock', '0013_alter_productos_impuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoscompras',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='pagoscompras',
            name='ingreso',
        ),
        migrations.AddField(
            model_name='cxpcompras',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='iva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='retencion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscompras',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.puc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscompras',
            name='diferenciaBanco',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pagoscompras',
            name='proveedor',
            field=models.ForeignKey(default=109, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proveedor', to='configuracion.terceros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscompras',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscompras',
            name='totalSaldoFavor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura:'),
        ),
        migrations.AlterField(
            model_name='pagoscompras',
            name='ValorAbono',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagoscompras',
            name='concepto',
            field=models.TextField(blank=True, null=True, verbose_name='Concepto:'),
        ),
        migrations.AlterField(
            model_name='pagoscompras',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha:'),
        ),
        migrations.CreateModel(
            name='DetailPaymentInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.CharField(max_length=50, verbose_name='Factura:')),
                ('descuento', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('totalAbono', models.FloatField()),
                ('cxpCompra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detailcxp', to='stock.cxpcompras')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_ingreso', to='stock.ingreso')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detailorden', to='stock.ordendecompra')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_compra', to='stock.pagoscompras')),
            ],
            options={
                'verbose_name': 'DetailPaymentInVoice',
                'verbose_name_plural': 'DetailPaymentInVoices',
                'db_table': 'detailpaymentinvoice',
            },
        ),
        migrations.CreateModel(
            name='DetailPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.puc')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallep_compra', to='stock.pagoscompras')),
            ],
            options={
                'verbose_name': 'DetailPayment',
                'verbose_name_plural': 'DetailPayments',
                'db_table': 'detailpayment',
            },
        ),
    ]
