# Generated by Django 4.0.2 on 2023-01-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_remove_pagoscompras_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenotacredito',
            name='laboratorio',
            field=models.CharField(default=0, max_length=50, verbose_name='Laboratorio:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notacredito',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
