# Generated by Django 4.0.2 on 2023-02-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_detallenotacredito_laboratorio_notacredito_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='bodega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bodega_tiposP', to='stock.bodega'),
            preserve_default=False,
        ),
    ]
