# Generated by Django 4.0.2 on 2023-03-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0016_tipoproducto_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='fecha',
            field=models.DateField(default=None, verbose_name='fecha:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notacredito',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='notaCreditoC_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
