# Generated by Django 4.0.2 on 2023-03-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_notacredito_fecha_notacredito_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='valorVenta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='valorventa1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='valorventa2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
