# Generated by Django 4.0.2 on 2023-03-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_puc_formapago'),
        ('stock', '0019_alter_productos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='c_gasto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_gasto', to='contabilidad.puc'),
            preserve_default=False,
        ),
    ]
