# Generated by Django 4.0.2 on 2023-03-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_tipoproducto_c_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='TIPO'),
        ),
    ]
