# Generated by Django 4.0.2 on 2023-04-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_remove_pagoscompras_valorabono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoscompras',
            name='fecha',
            field=models.DateField(verbose_name='Fecha:'),
        ),
    ]
