# Generated by Django 4.0.2 on 2023-04-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_alter_pagoscompras_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoscompras',
            name='tipoTransaccion',
            field=models.BooleanField(choices=[(0, 'Pago sin relación'), (1, 'Pago con relación')], verbose_name='Tipo de transaccion:'),
        ),
    ]
