# Generated by Django 4.0.2 on 2023-04-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_alter_pagoscompras_tipotransaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallenotacredito',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='ingresodetalle',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='laboratorio',
        ),
        migrations.AddField(
            model_name='productos',
            name='laboratorio',
            field=models.CharField(default='', max_length=150, verbose_name='Laboratorio:'),
            preserve_default=False,
        ),
    ]
