# Generated by Django 4.0.2 on 2023-05-29 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_remove_detallenotacredito_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencioningreso',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha'),
            preserve_default=False,
        ),
    ]
