# Generated by Django 4.0.2 on 2023-05-29 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_retencioningreso_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuestoingreso',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retencioningreso',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
