# Generated by Django 4.0.2 on 2023-05-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_impuestoingreso_fecha_alter_retencioningreso_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxpcompras',
            name='fecha',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha:'),
        ),
    ]
