# Generated by Django 4.0.2 on 2023-05-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_alter_cxpcompras_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxpcompras',
            name='factura',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Factura:'),
        ),
    ]
