# Generated by Django 4.0.2 on 2023-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_alter_cxpcompras_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscompras',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detailpaymentinvoice',
            name='factura',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Factura:'),
        ),
    ]
