# Generated by Django 4.0.2 on 2023-06-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_estadofinanciero'),
        ('stock', '0030_pagoscompras_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='c_costo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_costo', to='contabilidad.puc', verbose_name='Cuenta Costo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='c_ingreso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_ingreso', to='contabilidad.puc', verbose_name='Cuenta Ingreso:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kardex',
            name='fecha',
            field=models.DateField(verbose_name='fecha:'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='c_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_gasto', to='contabilidad.puc', verbose_name='Cuenta Gasto'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='c_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_tipo', to='contabilidad.puc', verbose_name='Cuenta inventario:'),
        ),
    ]
