# Generated by Django 4.0.2 on 2023-06-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_estadofinanciero'),
        ('stock', '0031_tipoproducto_c_costo_tipoproducto_c_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='c_dev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_dev_ingreso', to='contabilidad.puc', verbose_name='Cuenta Devolucion Ingreso:'),
            preserve_default=False,
        ),
    ]
