# Generated by Django 4.0.2 on 2023-07-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_tipoproducto_c_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxpcompras',
            name='notaCredito',
            field=models.BooleanField(default=False),
        ),
    ]
