# Generated by Django 4.0.2 on 2023-08-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_cxpcompras_notacredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetalle',
            name='iva',
            field=models.FloatField(),
        ),
    ]
