# Generated by Django 4.0.2 on 2023-08-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_alter_ingresodetalle_iva_alter_ordendetalle_iva'),
        ('stock', '0034_alter_ordendetalle_iva'),
    ]

    operations = [
    ]
