# Generated by Django 4.0.2 on 2023-08-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_alter_productos_cum'),
        ('stock', '0035_merge_20230824_1005'),
    ]

    operations = [
    ]
