# Generated by Django 4.0.2 on 2023-11-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_ajustestock_ajustedetalle'),
        ('stock', '0036_merge_20230828_0833'),
    ]

    operations = [
    ]
