# Generated by Django 4.0.2 on 2023-03-24 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_alter_puc_tipodecuenta'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_concepto', to='contabilidad.puc'),
        ),
    ]
