# Generated by Django 4.0.2 on 2023-03-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_alter_puc_tipodecuenta'),
        ('nomina', '0003_alter_concepto_cuenta_alter_concepto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto',
            name='contrapartida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concepto_cuentas_contra', to='contabilidad.puc'),
        ),
    ]
