# Generated by Django 4.0.2 on 2023-07-28 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomina', '0005_arl_cajacompensacion_contrato_sena_ingresorecurrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_contrato_creacion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_empleado_creacion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=60, unique=True, verbose_name='Documento:'),
        ),
    ]
