# Generated by Django 4.0.2 on 2023-07-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_contrato_usuario_empleado_foto_empleado_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fechaFinalContrato',
            field=models.DateField(default=None, verbose_name='Fecha final contrato:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='fechaInicioContrato',
            field=models.DateField(default=None, verbose_name='Fecha inicio contrato:'),
            preserve_default=False,
        ),
    ]
