# Generated by Django 4.0.2 on 2024-01-20 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_contrato_nocontrato_contrato_tipocontrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ingresosRecurrentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresoRecurrente_empleado', to='nomina.ingresorecurrente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DeduccionRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Salarial'), (2, 'No Salarial')], default=1, verbose_name='tipo: ')),
                ('valorMensual', models.FloatField(verbose_name='Valor Mensual:')),
                ('valorQuincenal', models.FloatField(verbose_name='Valor Quincena:')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deduccionRecurrente_conceptos', to='nomina.concepto')),
            ],
            options={
                'verbose_name': 'DeduccionRecurrente',
                'verbose_name_plural': 'DeduccionRecurrentes',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='deduccionesRecurrentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deduccionRecurrente_empleado', to='nomina.deduccionrecurrente'),
        ),
    ]
