# Generated by Django 4.0.2 on 2024-01-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0009_contrato_ingresosrecurrentes_alter_contrato_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='deduccionesRecurrentes',
        ),
        migrations.AddField(
            model_name='contrato',
            name='deduccionesRecurrentes',
            field=models.ManyToManyField(blank=True, null=True, related_name='deduccionRecurrente_empleado', to='nomina.DeduccionRecurrente'),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='ingresosRecurrentes',
        ),
        migrations.AddField(
            model_name='contrato',
            name='ingresosRecurrentes',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingresoRecurrente_empleado', to='nomina.IngresoRecurrente'),
        ),
    ]
