# Generated by Django 4.0.2 on 2023-01-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('estado', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Bogeda')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
            },
        ),
        migrations.CreateModel(
            name='IngresoCompras',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('estado', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaFactura', models.DateField(verbose_name='fecha Factura')),
                ('factura', models.CharField(max_length=50, unique=True, verbose_name='factura')),
                ('iva', models.FloatField()),
                ('descuento', models.FloatField()),
                ('retencion', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'IngresoCompras',
                'verbose_name_plural': 'IngresoCompras',
            },
        ),
        migrations.CreateModel(
            name='IngresoComprasDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=50, verbose_name='lote')),
                ('fechaVence', models.DateField(verbose_name='Fecha vencimiento:')),
                ('cantidad', models.IntegerField()),
                ('valorUnidad', models.FloatField()),
                ('iva', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'IngresoComprasDetalle',
                'verbose_name_plural': 'IngresoComprasDetalles',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('unidades', models.IntegerField()),
                ('lote', models.CharField(max_length=50, verbose_name='lote')),
                ('valorCompra', models.FloatField()),
                ('valorVenta', models.FloatField()),
                ('valorventa1', models.FloatField()),
                ('valorventa2', models.FloatField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Iventario',
                'verbose_name_plural': 'Iventarios',
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('estado', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripcion')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo')),
                ('tercero', models.IntegerField()),
                ('unidades', models.IntegerField()),
                ('balance', models.IntegerField(default=0)),
                ('precio', models.FloatField()),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('estado', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('estado', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.CharField(default='100', max_length=250)),
                ('iva', models.FloatField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha_vence')),
                ('descuento', models.FloatField()),
                ('retencion', models.FloatField()),
                ('total', models.FloatField()),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes de compras',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeCompraDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valorUnidad', models.FloatField()),
                ('iva', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'OrdenDeCompraDetalle',
                'verbose_name_plural': 'OrdenDeCompraDetalles',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('estado', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('invima', models.CharField(blank=True, max_length=30, null=True)),
                ('cum', models.CharField(blank=True, max_length=30, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('iva', models.FloatField(default=0)),
                ('codigoDeBarra', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
                ('nombreymarcaunico', models.CharField(blank=True, max_length=900, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidades', models.IntegerField()),
                ('valorCompra', models.FloatField()),
                ('lote', models.CharField(max_length=50, unique=True, verbose_name='lote')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'StockProducto',
                'verbose_name_plural': 'StockProductos',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha Creacion:')),
                ('estado', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70, verbose_name='nombre')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
