# Generated by Django 4.0.2 on 2023-01-07 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
        ('configuracion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_bodega', to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_producto', to='inventario.productos'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productos',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='productos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca'),
        ),
        migrations.AddField(
            model_name='productos',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.unidad'),
        ),
        migrations.AddField(
            model_name='productos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordendecompradetalle',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_detalle', to='inventario.ordendecompra'),
        ),
        migrations.AddField(
            model_name='ordendecompradetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_producto', to='inventario.productos'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_tercero', to='configuracion.terceros'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marca',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='marca',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kardex',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_bodega', to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productos'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresocomprasdetalle',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingreso_detalle', to='inventario.ingresocompras'),
        ),
        migrations.AddField(
            model_name='ingresocomprasdetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingreso_producto', to='inventario.productos'),
        ),
        migrations.AddField(
            model_name='ingresocompras',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='ingresocompras',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_ingreso', to='inventario.ordendecompra'),
        ),
        migrations.AddField(
            model_name='ingresocompras',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodega',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
