# Generated by Django 4.0.2 on 2023-01-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, verbose_name='codigo')),
                ('departamento', models.CharField(max_length=50, verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'Departamentos',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Logo:')),
                ('slogan', models.CharField(max_length=250, null=True, verbose_name='Slogan:')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razon Social')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo:')),
                ('nit', models.CharField(max_length=100, verbose_name='Nit:')),
                ('dv', models.CharField(max_length=5, verbose_name='Digito de verificación:')),
                ('actividadEconomica', models.CharField(max_length=50, verbose_name='Actividad economica:')),
                ('nombreComercial', models.CharField(max_length=100, verbose_name='Nombre comercial')),
                ('tipoPersona', models.CharField(choices=[('1', 'Persona natural'), ('2', 'Persona judirica')], max_length=5, verbose_name='Tipo de persona:')),
                ('obligaciones', models.CharField(default='R-99-PN', max_length=50, verbose_name='Obligaciones')),
                ('telefono', models.CharField(max_length=100, verbose_name='Tel::')),
                ('registroMercantil', models.CharField(max_length=50, verbose_name='registroMercantil')),
                ('correoContacto', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateTimeField(verbose_name='fecha Modificacion:')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='forma')),
                ('plazo', models.IntegerField(blank=True, null=True, verbose_name='Plazo en Dias')),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Forma de pago',
                'db_table': 'formasdepago',
            },
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre:')),
                ('porcentaje', models.FloatField()),
                ('base', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Impuestos',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'impuestos',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, verbose_name='codigo')),
                ('municipio', models.CharField(max_length=50, verbose_name='municipio')),
            ],
            options={
                'verbose_name': 'Municipios',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='numeracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDocumento', models.CharField(choices=[('1', 'FACTURA ELECTRÓNICA'), ('2', 'FACTURA POS'), ('3', 'NOTA CRÉDITO'), ('4', 'NOTA DÉBITO'), ('5', 'COMPROBANTE DE INGRESO'), ('6', 'COMPROBANTE DE EGRESO'), ('7', 'COTIZACIÓN'), ('8', 'ORDEN DE COMPRA'), ('9', 'PROFORMA'), ('10', 'DOCUMENTOS SOPORTE'), ('11', 'NOTA CRÉDITO COMPRAS'), ('12', 'NOTA DÉBITO COMPRAS'), ('13', 'AJUSTE DE INVENTARIO'), ('14', 'NOTA DE AJUSTE DOC. SOPORTE'), ('15', 'TRASLADO ENTRE UBICACIONES'), ('16', 'RECEPCIÓN DE COMPRAS'), ('17', 'COMPROBANTE CONTABLE')], max_length=5, verbose_name='Tipo de documento:')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre:')),
                ('prefijo', models.CharField(max_length=50, verbose_name='prefijo:')),
                ('proximaFactura', models.IntegerField(verbose_name='Próxima Factura:')),
                ('desde', models.IntegerField(verbose_name='Desde el número:')),
                ('hasta', models.IntegerField(verbose_name='Hasta el número:')),
                ('resolucion', models.CharField(max_length=500, verbose_name='Resolución:')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha vencimiento:')),
                ('estado', models.BooleanField(default=True, verbose_name='estado:')),
            ],
            options={
                'verbose_name': 'numeracion',
                'verbose_name_plural': 'numeraciones',
                'db_table': 'numeraciones',
            },
        ),
        migrations.CreateModel(
            name='PlazosDecuentosClientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quince', models.FloatField(default=0)),
                ('treinta', models.FloatField(default=0)),
                ('cuarentaYcinco', models.FloatField(default=0)),
                ('sesenta', models.FloatField(default=0)),
                ('noventa', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'PlazosCliente',
                'verbose_name_plural': 'PlazosClientes',
                'db_table': 'plazo_clientes',
            },
        ),
        migrations.CreateModel(
            name='PlazosDecuentosProveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quince', models.FloatField(default=0)),
                ('treinta', models.FloatField(default=0)),
                ('cuarentaYcinco', models.FloatField(default=0)),
                ('sesenta', models.FloatField(default=0)),
                ('noventa', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'PlazosProveedor',
                'verbose_name_plural': 'PlazosProveedores',
                'db_table': 'plazo_proveedor',
            },
        ),
        migrations.CreateModel(
            name='Retenciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre:')),
                ('porcentaje', models.FloatField()),
                ('base', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Retenciones',
                'verbose_name_plural': 'Retenciones',
                'db_table': 'retenciones',
            },
        ),
        migrations.CreateModel(
            name='RetencionesClientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fija', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Impuestos',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'retenciones_clientes',
            },
        ),
        migrations.CreateModel(
            name='RetencionesProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fija', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Impuestos',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'retenciones_proveedor',
            },
        ),
        migrations.CreateModel(
            name='Terceros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDocumento', models.CharField(max_length=70, verbose_name='tipoDocumento')),
                ('documento', models.CharField(max_length=50, unique=True, verbose_name='Documento')),
                ('dv', models.CharField(blank=True, max_length=5, null=True, verbose_name='Digito Verificacion')),
                ('nombreComercial', models.CharField(max_length=120, verbose_name='nombreComercial')),
                ('nombreContacto', models.CharField(max_length=120, verbose_name='nombreContacto')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('telefonoContacto', models.CharField(max_length=50, verbose_name='Tel:')),
                ('correoContacto', models.EmailField(max_length=254, verbose_name='Correo Contacto')),
                ('correoFacturas', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Contacto')),
                ('tipoPersona', models.CharField(choices=[('1', 'Persona natural'), ('2', 'Persona judirica')], max_length=5, verbose_name='Tipo Persona')),
                ('regimen', models.CharField(max_length=50, verbose_name='Regimen:')),
                ('obligaciones', models.CharField(default='R-99-PN', max_length=50, verbose_name='Obligaciones')),
                ('matriculaMercantil', models.CharField(max_length=50, verbose_name='matriculaMercantil')),
                ('codigoPostal', models.CharField(max_length=50, verbose_name='codigoPostal')),
                ('saldoAFavorProveedor', models.FloatField(blank=True, default=0, null=True)),
                ('saldoAFavorCliente', models.FloatField(blank=True, default=0, null=True)),
                ('isCliente', models.BooleanField(blank=True, default=False, null=True)),
                ('isProveedor', models.BooleanField(blank=True, default=False, null=True)),
                ('isContabilidad', models.BooleanField(blank=True, default=False, null=True)),
                ('isCompras', models.BooleanField(blank=True, default=False, null=True)),
                ('isPos', models.BooleanField(blank=True, default=False, null=True)),
                ('isElectronico', models.BooleanField(blank=True, default=False, null=True)),
                ('montoCreditoProveedor', models.FloatField(blank=True, default=0, null=True)),
                ('montoCreditoClientes', models.FloatField(blank=True, default=0, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='fecha Creacion:')),
                ('fecha_modificacion', models.DateField(blank=True, null=True, verbose_name='fecha Modificacion:')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'db_table': 'terceros',
            },
        ),
        migrations.CreateModel(
            name='VendedoresClientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre:')),
                ('meta', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores_clientes',
            },
        ),
    ]
