# Generated by Django 4.0.2 on 2023-01-07 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0001_initial'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedoresclientes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terceros',
            name='cuenta_saldo_a_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_saldo_cliente', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='cuenta_saldo_a_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_saldo_proveedor', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='cuenta_x_cobrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_cobrar_tercero', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='cuenta_x_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_pagar_tercero', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.departamentos'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='formaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tercero_formaPago', to='configuracion.formapago'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.municipios'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedor_tercero', to='configuracion.vendedoresclientes'),
        ),
        migrations.AddField(
            model_name='retencionesproveedor',
            name='retencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_retenciones', to='configuracion.retenciones'),
        ),
        migrations.AddField(
            model_name='retencionesproveedor',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retencion_proveedor', to='configuracion.terceros'),
        ),
        migrations.AddField(
            model_name='retencionesclientes',
            name='retencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_retenciones', to='configuracion.retenciones'),
        ),
        migrations.AddField(
            model_name='retencionesclientes',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retencion_cliente', to='configuracion.terceros'),
        ),
        migrations.AddField(
            model_name='retenciones',
            name='compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retencion_compras', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='retenciones',
            name='ventas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retencion_ventas', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='plazosdecuentosproveedores',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plazos_proveedores', to='configuracion.terceros'),
        ),
        migrations.AddField(
            model_name='plazosdecuentosclientes',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plazos_clientes', to='configuracion.terceros'),
        ),
        migrations.AddField(
            model_name='numeracion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeracion_empresa', to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos_municipios', to='configuracion.departamentos'),
        ),
        migrations.AddField(
            model_name='impuestos',
            name='compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuesto_compras', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='impuestos',
            name='ventas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuesto_ventas', to='contabilidad.puc'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.departamentos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.municipios'),
        ),
    ]
