# Generated by Django 4.0.2 on 2023-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='departamento',
            field=models.CharField(max_length=100, verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='municipio'),
        ),
    ]
