# Generated by Django 4.0.2 on 2023-01-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_alter_terceros_correocontacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='telefonoContacto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel:'),
        ),
    ]
