# Generated by Django 4.0.2 on 2023-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_alter_terceros_telefonocontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='matriculaMercantil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='matriculaMercantil'),
        ),
    ]
