# Generated by Django 4.0.2 on 2023-01-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_alter_terceros_matriculamercantil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='codigoPostal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='codigoPostal'),
        ),
    ]
