# Generated by Django 4.0.2 on 2023-01-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_alter_terceros_codigopostal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retencionesclientes',
            options={'verbose_name': 'Retenciones cliente', 'verbose_name_plural': 'Retenciones clientes'},
        ),
        migrations.AlterModelOptions(
            name='retencionesproveedor',
            options={'verbose_name': 'Retenciones proveedor', 'verbose_name_plural': 'Retenciones proveedores'},
        ),
    ]
