# Generated by Django 4.0.2 on 2023-02-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_terceros_isretencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeracion',
            name='tipoDocumento',
            field=models.CharField(choices=[('1', 'FACTURA ELECTRÓNICA'), ('2', 'FACTURA POS'), ('3', 'NOTA CRÉDITO'), ('4', 'NOTA DÉBITO'), ('5', 'COMPROBANTE DE INGRESO'), ('6', 'COMPROBANTE DE EGRESO'), ('7', 'COTIZACIÓN'), ('8', 'ORDEN DE COMPRA'), ('9', 'PROFORMA'), ('10', 'DOCUMENTOS SOPORTE'), ('11', 'NOTA CRÉDITO COMPRAS'), ('12', 'NOTA DÉBITO COMPRAS'), ('13', 'AJUSTE DE INVENTARIO'), ('14', 'NOTA DE AJUSTE DOC. SOPORTE'), ('15', 'TRASLADO ENTRE UBICACIONES'), ('16', 'RECEPCIÓN DE COMPRAS'), ('17', 'COMPROBANTE CONTABLE'), ('18', 'INGRESO AL ALMACEN')], max_length=5, verbose_name='Tipo de documento:'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='correoFacturas',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Facturas'),
        ),
    ]
