# Generated by Django 4.0.2 on 2023-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_listadeprecios_terceros_listaprecios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='tipoPersona',
            field=models.CharField(choices=[('2', 'Persona natural'), ('1', 'Persona judirica')], max_length=5, verbose_name='Tipo Persona'),
        ),
    ]
