# Generated by Django 4.0.2 on 2023-03-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_alter_terceros_tipopersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeracion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='fecha Inicio:'),
        ),
        migrations.AddField(
            model_name='numeracion',
            name='textoResolucion',
            field=models.CharField(default='', max_length=5000, verbose_name='Texto Resolución:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retenciones',
            name='tipoRetencion',
            field=models.CharField(choices=[('06', 'Retención en la fuente'), ('07', 'Impuesto de Industria y Comercio (ICA)')], default=1, max_length=5, verbose_name='Tipo de retención'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numeracion',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha vencimiento:'),
        ),
        migrations.AlterField(
            model_name='numeracion',
            name='resolucion',
            field=models.CharField(max_length=500, verbose_name='N° Resolución:'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='regimen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Regimen:'),
        ),
    ]
