# Generated by Django 4.0.2 on 2023-04-26 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0014_plazosdecuentosproveedores_cuarenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CONTABILIDAD', 'CONTABILIDAD'), ('FACTURACION', 'FACTURACIÓN'), ('COMPRAS', 'COMPRAS')], max_length=50, verbose_name='Tipo de contacto:')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('correo', models.CharField(max_length=50, verbose_name='correo:')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos_contacto', to='configuracion.terceros')),
            ],
            options={
                'verbose_name': 'Datos de contacto',
                'verbose_name_plural': 'Datos de contactos',
                'db_table': 'datos_contacto',
            },
        ),
    ]
