# Generated by Django 4.0.2 on 2023-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0016_datosbancarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontacto',
            name='telefono',
            field=models.CharField(default=3157393331, max_length=50, verbose_name='Nombre:'),
            preserve_default=False,
        ),
    ]
