# Generated by Django 4.0.2 on 2023-06-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0020_impuestosengeneral_tercero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencionesengeneral',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
