# Generated by Django 4.0.2 on 2023-10-18 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0026_alter_numeracion_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('grupo', models.CharField(blank=True, choices=[('CONTABILIDAD', 'CONTABILIDAD'), ('FACTURACIÓN', 'FACTURACION'), ('LOGÍSTICA', 'LOGISTICA')], max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('NORMAL', 'NORMAL'), ('PRECIOS_BAJOS', 'PRECIOS BAJOS'), ('DESPACHOS', 'DESPACHOS'), ('FACTURA', 'FACTURA'), ('INGRESO', 'INGRESO')], max_length=255)),
                ('receiver_users', models.ManyToManyField(related_name='receiver_user', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noti_user', to=settings.AUTH_USER_MODEL)),
                ('vistas', models.ManyToManyField(related_name='user_view', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
            },
        ),
    ]
