# Generated by Django 4.0.2 on 2023-10-19 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0027_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='receiver_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='receiver_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='vistas',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
