# Generated by Django 4.0.2 on 2023-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
