# Generated by Django 4.0.2 on 2023-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.CharField(blank=True, choices=[('CONTABILIDAD', 'CONTABILIDAD'), ('FACTURACION', 'FACTURACIÓN'), ('LOGISTICA', 'LOGÍSTICA'), ('GENERAL', 'GENERAL')], max_length=50),
        ),
    ]
