# Generated by Django 4.0.2 on 2023-10-19 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superusuario', models.BooleanField(default=False)),
                ('wtablas', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='permisos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permisos de Usuario',
                'verbose_name_plural': 'Permisos de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='SettingsPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crear_user', models.BooleanField(default=False)),
                ('ver_user', models.BooleanField(default=False)),
                ('permisos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings_permisos', to='users.permisosusuario')),
            ],
            options={
                'verbose_name': 'Permisos de Configuración',
                'verbose_name_plural': 'Permisos de Configuración',
            },
        ),
        migrations.CreateModel(
            name='PagosPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cxp', models.BooleanField(default=False)),
                ('egresos', models.BooleanField(default=False)),
                ('crear', models.BooleanField(default=False)),
                ('pagos', models.BooleanField(default=False)),
                ('permisos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_permisos', to='users.permisosusuario')),
            ],
            options={
                'verbose_name': 'Permisos de Pagos',
                'verbose_name_plural': 'Permisos de Pagos',
            },
        ),
        migrations.CreateModel(
            name='InventarioPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodegas', models.BooleanField(default=False)),
                ('orden', models.BooleanField(default=False)),
                ('crear_orden', models.BooleanField(default=False)),
                ('ingresar_orden', models.BooleanField(default=False)),
                ('productos', models.BooleanField(default=False)),
                ('listado_productos', models.BooleanField(default=False)),
                ('nota_credito', models.BooleanField(default=False)),
                ('crear_nota_credito', models.BooleanField(default=False)),
                ('ajuste', models.BooleanField(default=False)),
                ('consumo', models.BooleanField(default=False)),
                ('kardex', models.BooleanField(default=False)),
                ('permisos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_permisos', to='users.permisosusuario')),
            ],
            options={
                'verbose_name': 'Permisos de Inventario',
                'verbose_name_plural': 'Permisos de Inventario',
            },
        ),
        migrations.CreateModel(
            name='InformesPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_inventario', models.BooleanField(default=False)),
                ('inv_inventario_vencido', models.BooleanField(default=False)),
                ('oc_compras_detalladas', models.BooleanField(default=False)),
                ('oc_rotacion_productos', models.BooleanField(default=False)),
                ('oc_retenciones', models.BooleanField(default=False)),
                ('fac_rotacion_productos', models.BooleanField(default=False)),
                ('fac_ventas_detalladas', models.BooleanField(default=False)),
                ('fac_ventas_x_vendedor', models.BooleanField(default=False)),
                ('fac_retenciones', models.BooleanField(default=False)),
                ('conta_balance_prueba', models.BooleanField(default=False)),
                ('conta_estado_financiero', models.BooleanField(default=False)),
                ('conta_estado_resultado', models.BooleanField(default=False)),
                ('conta_libro_aux', models.BooleanField(default=False)),
                ('conta_cxc', models.BooleanField(default=False)),
                ('conta_cxp', models.BooleanField(default=False)),
                ('conta_abonos_recibidos', models.BooleanField(default=False)),
                ('cliente_estado_cartera', models.BooleanField(default=False)),
                ('cliente_cartera_vencida', models.BooleanField(default=False)),
                ('cliente_listado', models.BooleanField(default=False)),
                ('proveedor_estado_cartera', models.BooleanField(default=False)),
                ('proveedor_listado', models.BooleanField(default=False)),
                ('permisos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_permisos', to='users.permisosusuario')),
            ],
            options={
                'verbose_name': 'Permisos de Informes',
                'verbose_name_plural': 'Permisos de Informes',
            },
        ),
        migrations.CreateModel(
            name='FacturacionPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crear', models.BooleanField(default=False)),
                ('proforma', models.BooleanField(default=False)),
                ('cotizacion', models.BooleanField(default=False)),
                ('listado', models.BooleanField(default=False)),
                ('despachos', models.BooleanField(default=False)),
                ('nota_credito', models.BooleanField(default=False)),
                ('nota_debito', models.BooleanField(default=False)),
                ('firmar_factura', models.BooleanField(default=False)),
                ('dar_alta_factura', models.BooleanField(default=False)),
                ('permisos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturacion_permisos', to='users.permisosusuario')),
            ],
            options={
                'verbose_name': 'Permisos de Facturación',
                'verbose_name_plural': 'Permisos de Facturación',
            },
        ),
        migrations.CreateModel(
            name='EmpleadosPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crear', models.BooleanField(default=False)),
                ('listado', models.BooleanField(default=False)),
                ('permisos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados_permisos', to='users.permisosusuario')),
            ],
            options={
                'verbose_name': 'Permisos de Empleados',
                'verbose_name_plural': 'Permisos de Empleados',
            },
        ),
        migrations.CreateModel(
            name='ContabilidadPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puc', models.BooleanField(default=False)),
                ('comprobantes_contables', models.BooleanField(default=False)),
                ('informes', models.BooleanField(default=False)),
                ('libro_auxiliar', models.BooleanField(default=False)),
                ('conciliacion', models.BooleanField(default=False)),
                ('traslados', models.BooleanField(default=False)),
                ('permisos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contabilidad_permisos', to='users.permisosusuario')),
            ],
            options={
                'verbose_name': 'Permisos de Contabilidad',
                'verbose_name_plural': 'Permisos de Contabilidad',
            },
        ),
        migrations.CreateModel(
            name='CobrosPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cxc', models.BooleanField(default=False)),
                ('ingreso', models.BooleanField(default=False)),
                ('crear', models.BooleanField(default=False)),
                ('permisos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_permisos', to='users.permisosusuario')),
            ],
            options={
                'verbose_name': 'Permisos de Cobros',
                'verbose_name_plural': 'Permisos de Cobros',
            },
        ),
    ]
